### ISSUE TITLE
Installation Issues with libnlopt.0.dylib on OSX

### ISSUE THREAD

**Issue by bicep** [esa/pagmo2#208]
Hello,

I have followed the installation instructions using Miniconda on High Sierra OSX, and I am unable to get the quickstart.py example to work. Pgymo is recognized as a library but errors are thrown.

These are my steps
```
conda create -n myenv python=3.6
conda config --add channels conda-forge
conda install -n myenv pygmo
source activate myenv
```

This is the error message I get when I run `python quickstart.py`:
```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    import pygmo as pg
  File "/Users/rogerko/miniconda3/envs/myenv/lib/python3.6/site-packages/pygmo/__init__.py", line 38, in <module>
    from .core import *
ImportError: dlopen(/Users/rogerko/miniconda3/envs/myenv/lib/python3.6/site-packages/pygmo/core.so, 2): Library not loaded: @rpath/libnlopt.0.dylib
  Referenced from: /Users/rogerko/miniconda3/envs/myenv/lib/python3.6/site-packages/pygmo/core.so
  Reason: Incompatible library version: core.so requires version 9.0.0 or later, but libnlopt.0.dylib provides version 0.0.0
```
Seems like the correct nlopt library is not being linked, but then it was definitely installed by Conda. Here is `conda list`:

```
               0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
boost                     1.67.0           py36h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
eigen                     3.3.5                hfc679d8_1    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
ipopt                     3.12.10         blas_openblash1727795_0  [blas_openblas]  conda-forge
ipykernel                 4.8.2                    py36_0    conda-forge
ipyparallel               6.2.2                    py36_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libffi                    3.2.1                hfc679d8_4    conda-forge
libgfortran               3.0.0                         0    conda-forge
libgfortran-ng            3.0.1                h93005f0_2  
libsodium                 1.0.16                        0    conda-forge
metis                     5.1.0                         3    conda-forge
mumps                     5.0.2           blas_openblash613969f_210  [blas_openblas]  conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
nlopt                     2.5.0            py36hf8a1672_0    conda-forge
numpy                     1.15.0          py36_blas_openblashd3ea46f_200  [blas_openblas]  conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2o               h470a237_1    conda-forge
pagmo                     2.8                  h83d4a3d_0    conda-forge
parso                     0.3.1                      py_0    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       18.0                     py36_1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pygmo                     2.8              py36h5c5fb89_0    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pyzmq                     17.1.2           py36hae99301_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
scotch                    6.0.5                h9c0d707_1    conda-forge
setuptools                40.0.0                   py36_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tk                        8.6.8                         0    conda-forge
tornado                   5.1              py36h470a237_1    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

```

**Comment by bluescarni** [comment]
Is it possible that you have another nlopt dynamic library lying around that gets picked up instead of the conda one?

**Comment by bicep** [comment]
Thanks for the quick reply!

So when I go to /miniconda3/envs/myenv/lib and delete the libnlopt.0.dylib file, then run `python quickstart.py` again I get a different error:

```
Traceback (most recent call last):
  File "quickstart.py", line 1, in <module>
    import pygmo as pg
  File "/Users/rogerko/miniconda3/envs/Opossum/lib/python3.6/site-packages/pygmo/__init__.py", line 38, in <module>
    from .core import *
ImportError: dlopen(/Users/rogerko/miniconda3/envs/myenv/lib/python3.6/site-packages/pygmo/core.so, 2): Library not loaded: @rpath/libnlopt.0.dylib
  Referenced from: /Users/rogerko/miniconda3/envs/myenv/lib/python3.6/site-packages/pygmo/core.so
  **Reason: image not found**
```
So I am sure that it is the dynamic library in the env myenv that is being linked to pygmo. 

But I could be wrong, any idea how to check more robustly?

**Comment by bluescarni** [comment]
I don't use OSX myself, so I am afraid I cannot say with certainty. In linux one can use ``ldd`` to check the dynamic libraries dependency chain, and I believe that in OSX a roughly equivalent tool is ``otool``:

https://www.unix.com/man-page/osx/1/otool/

It is however possible that the nlopt package in conda was recently updated in a non-backward compatible manner, at least on OSX, and if that's the case I am hopeful we can fix it just by triggering a rebuild of the pygmo package on conda-forge. I'll investigate a bit.

**Comment by bluescarni** [comment]
It turns out nlopt was indeed recently updated to version 2.5 on conda-forge. I have opened up a PR for re-building pygmo here:

https://github.com/conda-forge/pygmo-feedstock/pull/22

Let's see how it goes...

**Comment by bluescarni** [comment]
Could you try to update pygmo in your conda installation? I think the rebuild might have solved the issue.

**Comment by bicep** [comment]
Yes I've just updated and it works!
Thank you for your help 😄

**Comment by bluescarni** [comment]
No problem, thanks for taking the time to report the issue!
